### ISSUE TITLE
Where could I find the paper?

### ISSUE THREAD

**Issue by zzwei1** [researchmm/FTVSR#1]
Nice work! 
However, based on the title, I could not find the corresponding paper on google scholar or arxiv. Where could I find the paper?

**Comment by hyang0511** [comment]
Hi, we plan to submit this paper to arXiv before the official ECCV release. I will let you know once it is ready.

**Comment by zzwei1** [comment]
> 

Thanks!

**Comment by qiuzhongwei-USTB** [comment]
thanks for your interest in our work. Now you can find the paper on arxiv.
