### ISSUE TITLE
When we execute the test code of REDS4，have some mistakes. 

### ISSUE THREAD

**Issue by StevenTony611** [researchmm/FTVSR#10]
KeyError: 'TTVSR is not in the model registry'. 
We cannot find the TTVSR model in the released code, we doubt the released code is incomplete so we cannot execute the test code successfully. If possible, please the author to review this released code. Thank you!!!

**Comment by qiuzhongwei-USTB** [comment]
could you provide the error logs and you running config/command?

**Comment by StevenTony611** [comment]
There are the  running command and error logs:
(FTVSR003) zqiang@server-03:~/FTVSR-main$ CUDA_VISIBLE_DEVICES=0    python    ./tools/test.py  configs/FTVSR_reds4.py model/FTVSR_REDS.pth   --save-path  Save_
Traceback (most recent call last):
  File "./tools/test.py", line 229, in <module>
    main()
  File "./tools/test.py", line 151, in main
    model = build_model(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/share4/home/zqiang/FTVSRmmediting02/mmedit/models/builder.py", line 60, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/share4/home/zqiang/FTVSRmmediting02/mmedit/models/builder.py", line 22, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'TTVSR is not in the model registry'

Thank you!!!

**Comment by StevenTony611** [comment]
The config file is https://github.com/researchmm/FTVSR/blob/main/configs/FTVSR_reds4.py.

**Comment by StevenTony611** [comment]
When we execute the test code of Vimeo90K, we also have got some mistakes, it's so confusing...

(FTVSR003) zqiang@server-04:~/FTVSR-main$ CUDA_VISIBLE_DEVICES=6   python   ./tools/test.py configs/FTVSR_vimeo90k.py   model/FTVSR_Vimeo90K.pth   --save-path  Save_
Traceback (most recent call last):
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() missing 1 required positional argument: 'ann_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 229, in <module>
    main()
  File "./tools/test.py", line 136, in main
    dataset = build_dataset(cfg.data.test)
  File "/share4/home/zqiang/FTVSRmmediting02/mmedit/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SRVid4Dataset: __init__() missing 1 required positional argument: 'ann_file'

We really need the correct version for achieving the FTVSR successfully！  Thank you very much!!!

**Comment by StevenTony611** [comment]
When we execute the test code of Vimeo90K with multi GPU, we also have got some other mistakes. 
This reason may be the dataset setting of  'calendar_0_0', 'calendar_0_1','calendar_1_0','calendar_1_1'. We don't know why to change the test datasets to '_0_0' format.  It's so confusing....

==================================================================================
(FTVSR003) zqiang@server-04:~/FTVSR-main$ CUDA_VISIBLE_DEVICES=6,7   ./tools/dist_test.sh configs/FTVSR_vimeo90k.py   model/FTVSR_Vimeo90K.pth  2  --save-path  Save_
/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************





2022-09-10 04:40:58,017 - mmedit - INFO - Use load_from_http loader





Use load_from_local loader
Use load_from_local loader
[                                                  ] 0/16, elapsed: 0s, ETA:/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[>>>>>>>>>>>>>>>>>>                                ] 6/16, 0.0 task/s, elapsed: 348s, ETA:   580sTraceback (most recent call last):
  File "./tools/test.py", line 229, in <module>
    main()
  File "./tools/test.py", line 191, in main
    empty_cache=empty_cache)
  File "/share4/home/zqiang/FTVSR-main/mmedit/apis/test.py", line 108, in multi_gpu_test
    **data)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/core/distributed_wrapper.py", line 113, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/basic_restorer.py", line 74, in forward
    return self.forward_test(lq, gt, qp, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/ttvsr.py", line 179, in forward_test
    output = self.generator(lq)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/backbones/sr_backbones/ftvsr.py", line 132, in forward
    'The height and width of inputs should be at least 64, '
AssertionError: The height and width of inputs should be at least 64, but got 60 and 88.
[>>>>>>>>>>>>>>>>>>>>>>>>>                         ] 8/16, 0.0 task/s, elapsed: 414s, ETA:   414sTraceback (most recent call last):
  File "./tools/test.py", line 229, in <module>
    main()
  File "./tools/test.py", line 191, in main
    empty_cache=empty_cache)
  File "/share4/home/zqiang/FTVSR-main/mmedit/apis/test.py", line 108, in multi_gpu_test
    **data)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/core/distributed_wrapper.py", line 113, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/basic_restorer.py", line 74, in forward
    return self.forward_test(lq, gt, qp, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/ttvsr.py", line 179, in forward_test
    output = self.generator(lq)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share4/home/zqiang/FTVSR-main/mmedit/models/backbones/sr_backbones/ftvsr.py", line 132, in forward
    'The height and width of inputs should be at least 64, '
AssertionError: The height and width of inputs should be at least 64, but got 60 and 88.

**Comment by StevenTony611** [comment]
We have another question: 
training the FTVSR needing GPU requirement, how many GPU numbers and GPU memory can be trained successfully?

**Comment by qiuzhongwei-USTB** [comment]
> dataset = build_from_cfg(cfg, DATASETS, default_args)

The code works fine on our machine. Maybe there are some environmental problems?

**Comment by qiuzhongwei-USTB** [comment]
> When we execute the test code of Vimeo90K with multi GPU, we also have got some other mistakes. This reason may be the dataset setting of 'calendar_0_0', 'calendar_0_1','calendar_1_0','calendar_1_1'. We don't know why to change the test datasets to '_0_0' format. It's so confusing....
> 
> ================================================================================== (FTVSR003) zqiang@server-04:~/FTVSR-main$ CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_test.sh configs/FTVSR_vimeo90k.py model/FTVSR_Vimeo90K.pth 2 --save-path Save_ /share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> FutureWarning, WARNING:torch.distributed.run:
> 
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> 
> 2022-09-10 04:40:58,017 - mmedit - INFO - Use load_from_http loader
> 
> Use load_from_local loader Use load_from_local loader [ ] 0/16, elapsed: 0s, ETA:/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/TensorShape.cpp:2228.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] /share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/TensorShape.cpp:2228.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] [>>>>>>>>>>>>>>>>>> ] 6/16, 0.0 task/s, elapsed: 348s, ETA: 580sTraceback (most recent call last): File "./tools/test.py", line 229, in main() File "./tools/test.py", line 191, in main empty_cache=empty_cache) File "/share4/home/zqiang/FTVSR-main/mmedit/apis/test.py", line 108, in multi_gpu_test **data) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/core/distributed_wrapper.py", line 113, in forward return self.module(*inputs[0], **kwargs[0]) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func return old_func(*args, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/basic_restorer.py", line 74, in forward return self.forward_test(lq, gt, qp, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/ttvsr.py", line 179, in forward_test output = self.generator(lq) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward output = self.module(*inputs[0], **kwargs[0]) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/backbones/sr_backbones/ftvsr.py", line 132, in forward 'The height and width of inputs should be at least 64, ' AssertionError: The height and width of inputs should be at least 64, but got 60 and 88. [>>>>>>>>>>>>>>>>>>>>>>>>> ] 8/16, 0.0 task/s, elapsed: 414s, ETA: 414sTraceback (most recent call last): File "./tools/test.py", line 229, in main() File "./tools/test.py", line 191, in main empty_cache=empty_cache) File "/share4/home/zqiang/FTVSR-main/mmedit/apis/test.py", line 108, in multi_gpu_test **data) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/core/distributed_wrapper.py", line 113, in forward return self.module(*inputs[0], **kwargs[0]) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func return old_func(*args, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/basic_restorer.py", line 74, in forward return self.forward_test(lq, gt, qp, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/restorers/ttvsr.py", line 179, in forward_test output = self.generator(lq) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward output = self.module(*inputs[0], **kwargs[0]) File "/share4/home/zqiang/anaconda3/envs/FTVSR003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share4/home/zqiang/FTVSR-main/mmedit/models/backbones/sr_backbones/ftvsr.py", line 132, in forward 'The height and width of inputs should be at least 64, ' AssertionError: The height and width of inputs should be at least 64, but got 60 and 88.

Please remove the limitation of input size. We have updated the codes.

**Comment by qiuzhongwei-USTB** [comment]
> We have another question: training the FTVSR needing GPU requirement, how many GPU numbers and GPU memory can be trained successfully?

We use 8 V100 with 32G memory.
