### ISSUE TITLE
Question on inference test

### ISSUE THREAD

**Issue by AGenchev** [researchmm/FTVSR#12]
Hello !
I tried to run inference to compare to other VSR networks, but I run out of memory where other networks worked.
What I do is: in a notebook prepare 20 frames of 512x384 and feed this to the model.
This crashes with OOM on GPU w 24GB CUDA memory. At home I don't have bigger GPU.
So does your model require more memory or I am not testing it like it should be done ?
AFAIK the more frames you feed at once, the better result can be expected, is this true ?

**Comment by qiuzhongwei-USTB** [comment]
1. Based on the current dataset results, we found that the longer the input sequence, the better results we can obtain.
2. we use 32GB V100 or 40GB A100 for testing.

**Comment by AGenchev** [comment]
Thank you for clarification and keep the good work!
I close this issue as solved.
