### ISSUE TITLE
Training time for 400k iterations

### ISSUE THREAD

**Issue by caide199212** [researchmm/FTVSR#17]
Nice work!  And I'am trying to reproduce the training with Reds dataset on **4 GPU**(each with 16G memory). The batchsize is set  1 as suggested in the config file. The total training time looks to be ~31 days. I'm wondering if this is case for your training or I'm wrong somewhere.

Thanks a lot.

**Comment by qiuzhongwei-USTB** [comment]
We use 8 V100 GPUs with 32GB. 
The performance is depended on the sequence length you used for training (1-100).
with 20imgs/sequence, it cost about 7 days for training.

**Comment by caide199212** [comment]
Got it. Thank you very much for your prompt reply.
