### ISSUE TITLE
Out of memory in evaluation after train epochs

### ISSUE THREAD

**Issue by caide199212** [researchmm/FTVSR#18]
When reproducing the REDS datasets, I reduced the num_input_frames=20 to fit the GPU memory, so the training is fine, 8G is used for every 16G GPU.
![企业微信截图_16770536907007](https://user-images.githubusercontent.com/24669435/220562644-2f89f1b1-7f99-4bb4-82e5-86c6cda68c11.png)
But when it's evaluating, the GPU consumed by the training iteration seems **not released**. So the evaluation encounters the OOM as  
`RuntimeError: CUDA out of memory. Tried to allocate 436.00 MiB (GPU 1; 15.90 GiB total capacity; 10.98 GiB already allocated; 189.81 MiB free; 14.78 GiB reserved in total by PyTorch)`
![企业微信截图_16770537214755](https://user-images.githubusercontent.com/24669435/220563940-7453793b-24ba-47ec-b6a6-b3bb1219e573.png)

The config file for the data is as below:
`data = dict(
    workers_per_gpu=4,
    train_dataloader=dict(samples_per_gpu=1, drop_last=True),  
    test_dataloader=dict(samples_per_gpu=1, workers_per_gpu=1),`
   
    
   BTW, similar problem was reported in [mmdet](https://github.com/open-mmlab/mmdetection/issues/3052) but no feasible solutions was found.

**Comment by qiuzhongwei-USTB** [comment]
I don't know how to solve this problem.
Maybe you can skip the evaluation during the training process.

**Comment by caide199212** [comment]
Good idea, thanks.

**Comment by sunyclj** [comment]
> I don't know how to solve this problem.
> Maybe you can skip the evaluation during the training process.

when setting code  to evaluation = dict(interval=1000000, save_image=False, gpu_collect=True)，the same error occurs.
