### ISSUE TITLE
How  to split the 50% uncompressed videos and 50% compressed videos in training dataset?

### ISSUE THREAD

**Issue by StevenTony611** [researchmm/FTVSR#7]
In the paper, we got the training dataset split two parts: 50% uncompressed videos and 50% compressed videos, but we can't find how to split the training dataset. It's so confusing!

**Comment by qiuzhongwei-USTB** [comment]
please see the function 

`def folder_change1(folder):
    if 'X4' in folder:
        if np.random.uniform() > 0.5:
            pass
        else:
            crf_folder_choice = random.choice([0,15,25,35])
            folder = folder.replace('X4_start1', CRF_FOLDER[crf_folder_choice])
    elif 'sequences_BD' in folder:
        if np.random.uniform() > 0.5:
            pass
        else:
            crf_folder_choice = random.choice([0,15,25,35])
            folder = folder.replace('sequences_BD', VIMO[crf_folder_choice])
    else:
        raise ValueError('please check dataset: {}'.format(folder))
    return folder`

in [https://github.com/researchmm/FTVSR/blob/main/mmedit/datasets/base_sr_dataset.py](url)

**Comment by qiuzhongwei-USTB** [comment]
line 27-42 in [https://github.com/researchmm/FTVSR/blob/main/mmedit/datasets/base_sr_dataset.py](url)

**Comment by StevenTony611** [comment]
We find this function now and thank you very much！ Good job！
