### ISSUE TITLE
What dose the mean of dataset name?

### ISSUE THREAD

**Issue by StevenTony611** [researchmm/FTVSR#9]
For example, the vid4 dataset name is the 'calendar_0_0', 'calendar_0_1', 'calendar_1_0', 'calendar_1_1', what dose the mean of the "_0_0" in "./data/vid4/BD_start_1_crf_25/calendar_0_0". Thank you!

**Comment by qiuzhongwei-USTB** [comment]
We've described that clearly in the paper. Please Please refer to our paper, which shows that we crop images into 4 × 4 patches for inference since the limitation of CUDA memory.
